import "package:flutter/material.dart";
import "package:flutter_bloc/flutter_bloc.dart";
import "package:recipe_app/core/core.dart";
import "package:recipe_app/features/categories/presentation/widgets/recipe_bottom_navigationbar.dart";
import "package:recipe_app/features/review/presentation/manager/reviews/reviews_bloc.dart";
import "package:recipe_app/features/review/presentation/manager/reviews/reviews_state.dart";
import 'package:recipe_app/features/review/presentation/widgets/review_recipe.dart';
import 'package:recipe_app/features/review/presentation/widgets/reviews_comment.dart';
import 'package:recipe_app/features/review/presentation/widgets/recipe_review_app_bar.dart';
